---
sudo: required
dist: focal
language: python
python:
  - "3.6"
services:
  - docker
before_install:
  - sudo apt-get -qq update
install:
  - pip install molecule[docker] ansible ansible-lint flake8 testinfra
  # - pip install docker-py
script:
  - molecule test
