---
sudo: required
dist: xenial
language: python
python:
  - "2.7"
services:
  - docker
before_install:
  - sudo apt-get -qq update
install:
  - pip install molecule[docker] ansible-lint flake8 testinfra
  # - pip install docker-py
script:
  - molecule test
