---
- name: Create the Python installation group
  group:
    name: "{{ python_group }}"
  become: true

- name: Create the Python installation owner
  user:
    name: "{{ python_user }}"
    group: "{{ python_group }}"
  become: true

- name: Install dependencies (RedHat distros)
  yum:
    name:
      - bzip2-devel
      - gcc
      - gdbm-devel
      - libdb
      - libdb-devel
      - libffi-devel
      - libuuid-devel
      - make
      - ncurses
      - ncurses-devel
      - ncurses-libs
      - openssl-devel
      - readline-devel
      - sqlite-devel
      - tar
      - tcl-devel
      - tk-devel
      - xz
      - xz-devel
    state: present
  become: true
  retries: 3
  delay: 3
  when: ansible_facts['os_family'] == "RedHat"

- name: Install dependencies (Ubuntu)
  apt:
    name:
      - libbz2-dev
      - gcc
      - libgdbm-dev
      - libdb-dev
      - libffi-dev
      - uuid-dev
      - make
      - libncurses-dev
      - libssl-dev
      - libreadline-dev
      - libsqlite3-dev
      - tar
      - tcl-dev
      - tk-dev
      - libxv-dev
      - liblzma-dev
    state: present
  become: true
  retries: 3
  delay: 3
  when: ansible_facts['distribution'] == "Ubuntu"

- name: Delete source directory
  file:
    path: "{{ python_src_dir }}"
    state: absent
  become: true
  when: python_force

- name: Create source directory
  file:
    group: "{{ python_group }}"
    mode: 0755
    owner: "{{ python_user }}"
    path: "{{ python_src_dir }}"
    state: directory
  become: true

- name: Remove the archive
  file:
    path: "{{ python_src_dir }}/{{ python_archive }}"
    state: absent
  become: true
  when: python_force

- name: Check the archive isn't already available
  stat:
    path: "{{ python_src_dir }}/{{ python_archive }}"
  register: archive_stat_result

- name: Download the source archive
  get_url:
    dest: "{{ python_src_dir }}"
    group: "{{ python_group }}"
    owner: "{{ python_user }}"
    url: "{{ python_url }}"
  become: true
  retries: 3
  delay: 3
  when: not archive_stat_result.stat.exists

- name: Unpack the Python source archive
  unarchive:
    src: "{{ python_src_dir }}/{{ python_archive }}"
    dest: "{{ python_src_dir }}"
    group: "{{ python_group }}"
    owner: "{{ python_user }}"
    mode: 0755
    remote_src: true
  become: true

- name: Check configure hasn't run
  stat:
    path: "{{ python_src_dir }}/Python-{{ python_release }}/config.log"
  register: configure_stat_result

- name: Run ./configure
  command: >
    ./configure --prefix={{ python_install_dir }}/Python-{{
    python_minor }} chdir={{ python_src_dir }}/Python-{{ python_release }}
  become: true
  become_user: "{{ python_user }}"
  register: configure_result
  when: not configure_stat_result.stat.exists

- name: Run make
  make:
    chdir: "{{ python_src_dir }}/Python-{{ python_release }}"
  become: true
  become_user: "{{ python_user }}"
  register: make_result
  when: configure_result is not skipped

- name: Delete installation directory
  file:
    path: "{{ python_install_dir }}/Python-{{ python_minor }}"
    state: absent
  become: true
  when: python_force and make_result is not skipped

- name: Run make install
  make:
    chdir: "{{ python_src_dir }}/Python-{{ python_release }}"
    target: install
  become: true
  register: install_result
  when: make_result is not skipped

- name: Set permissions
  file:
    path: "{{ python_install_dir }}/Python-{{ python_minor }}"
    owner: "{{ python_user }}"
    group: "{{ python_group }}"
    recurse: true
  become: true
  when: install_result is not skipped
