---
- name: Converge
  hosts: all
  roles:
    - role: nmusatti.source_python
      vars:
        python_release: 3.7.0
  tasks:
    - name: Include role
      ansible.builtin.include_role:
        name: nmusatti.source_python
      vars:
        python_release: 3.7.1
        python_force: true
